var RushApp = angular.module('RushApp', []);


RushApp.controller('RushController', ['$scope', function ($scope) {

$scope.songs = [

{ album: 'Rush', name: 'Finding My Way', rating: 10 },
{ album: 'Rush', name: 'Need Some Love', rating: 9 },
{ album: 'Rush', name: 'Take A Friend', rating: 7 },
{ album: 'Rush', name: 'Here Again', rating: 10 },
{ album: 'Rush', name: 'What You\'re Doing', rating: 6 },
{ album: 'Rush', name: 'In The Mood', rating: 7 },
{ album: 'Rush', name: 'Before and After', rating: 8 },
{ album: 'Rush', name: 'Working Man', rating: 8 },

{ album: 'Fly By Night', name: 'Anthem', rating: 7 },
{ album: 'Fly By Night', name: 'Best I Can', rating: 6 },
{ album: 'Fly By Night', name: 'Beneath, Between and Behind', rating: 7 },
{ album: 'Fly By Night', name: 'By-Tor and the Snowdog', rating: 10 },
{ album: 'Fly By Night', name: 'Fly By Night', rating: 10 },
{ album: 'Fly By Night', name: 'Making Memories', rating: 7 },
{ album: 'Fly By Night', name: 'Rivendell', rating: 6 },
{ album: 'Fly By Night', name: 'In The End', rating: 10 },

{ album: 'Caress of Steel', name: 'Bastille Day', rating: 7 },
{ album: 'Caress of Steel', name: 'I Think I\'m Going Bald', rating: 5 },
{ album: 'Caress of Steel', name: 'Lakeside Park', rating: 6 },
{ album: 'Caress of Steel', name: 'The Necromancer', rating: 8 },
{ album: 'Caress of Steel', name: 'The Fountain of Lamneth', rating: 8 },

{ album: '2112', name: '2112', rating: 10 },
{ album: '2112', name: 'A Passage to Bangkok', rating: 6 },
{ album: '2112', name: 'The Twilight Zone', rating: 5 },
{ album: '2112', name: 'Lessons', rating: 6 },
{ album: '2112', name: 'Tears', rating: 7 },
{ album: '2112', name: 'Something For Nothing', rating: 9 },

{ album: 'A Farewell to Kings', name: 'A Farewell to Kings', rating: 10 },
{ album: 'A Farewell to Kings', name: 'Xanadu', rating: 10 },
{ album: 'A Farewell to Kings', name: 'Closer To The Heart', rating: 10 },
{ album: 'A Farewell to Kings', name: 'Cinderella Man', rating: 7 },
{ album: 'A Farewell to Kings', name: 'Madrigal', rating: 5 },
{ album: 'A Farewell to Kings', name: 'Cygnus X-1: Book I: The Voyage', rating: 10 },

{ album: 'Hemispheres', name: 'Cygnus X-1 Book Two: Hemispheres', rating: 7 },
{ album: 'Hemispheres', name: 'Circumstances', rating: 10 },
{ album: 'Hemispheres', name: 'The Trees', rating: 8 },
{ album: 'Hemispheres', name: 'La Villa Strangiato An Exercise in Self-Indulgence', rating: 10 },

{ album: 'Permanent Waves', name: 'The Spirit of Radio', rating: 10 },
{ album: 'Permanent Waves', name: 'Freewill', rating: 10 },
{ album: 'Permanent Waves', name: 'Jacob\'s Ladder', rating: 10 },
{ album: 'Permanent Waves', name: 'Entre Nous', rating: 10 },
{ album: 'Permanent Waves', name: 'Different Strings', rating: 10 },
{ album: 'Permanent Waves', name: 'Natural Science', rating: 10 },

{ album: 'Moving Pictures', name: 'Tom Sawyer', rating: 10 },
{ album: 'Moving Pictures', name: 'Red Barchetta', rating: 10 },
{ album: 'Moving Pictures', name: 'YYZ', rating: 10 },
{ album: 'Moving Pictures', name: 'Limelight', rating: 10 },
{ album: 'Moving Pictures', name: 'The Camera Eye', rating: 10 },
{ album: 'Moving Pictures', name: 'Witch Hunt Part III of Fear', rating: 7 },
{ album: 'Moving Pictures', name: 'Vital Signs', rating: 10 },

{ album: 'Signals', name: 'Subdivisions', rating: 8 },
{ album: 'Signals', name: 'The Analog Kid', rating: 8 },
{ album: 'Signals', name: 'Chemistry', rating: 9 },
{ album: 'Signals', name: 'Digital Man', rating: 7 },
{ album: 'Signals', name: 'The Weapon Part II of Fear', rating: 6 },
{ album: 'Signals', name: 'New World Man', rating: 7 },
{ album: 'Signals', name: 'Losing It', rating: 6 },
{ album: 'Signals', name: 'Countdown', rating: 8 },

{ album: 'Grace Under Pressure', name: 'Distant Early Warning', rating: 6 },
{ album: 'Grace Under Pressure', name: 'Afterimage', rating: 6 },
{ album: 'Grace Under Pressure', name: 'Red Sector A', rating: 7 },
{ album: 'Grace Under Pressure', name: 'The Enemy Within Part I of Fear', rating: 9 },
{ album: 'Grace Under Pressure', name: 'The Body Electric', rating: 8 },
{ album: 'Grace Under Pressure', name: 'Kid Gloves', rating: 8 },
{ album: 'Grace Under Pressure', name: 'Red Lenses', rating: 6 },
{ album: 'Grace Under Pressure', name: 'Between the Wheels', rating: 8 },

{ album: 'Power Windows', name: 'The Big Money', rating: 6 },
{ album: 'Power Windows', name: 'Grand Designs', rating: 7 },
{ album: 'Power Windows', name: 'Manhattan Project', rating: 7 },
{ album: 'Power Windows', name: 'Marathon', rating: 8 },
{ album: 'Power Windows', name: 'Territories', rating: 7 },
{ album: 'Power Windows', name: 'Middletown Dreams', rating: 6 },
{ album: 'Power Windows', name: 'Emotion Detector', rating: 7 },
{ album: 'Power Windows', name: 'Mystic Rhythms', rating: 8 },

{ album: 'Hold Your Fire', name: 'Force Ten', rating: 7 },
{ album: 'Hold Your Fire', name: 'Time Stand Still', rating: 8 },
{ album: 'Hold Your Fire', name: 'Open Secrets', rating: 6 },
{ album: 'Hold Your Fire', name: 'Second Nature', rating: 6 },
{ album: 'Hold Your Fire', name: 'Prime Mover', rating: 6 },
{ album: 'Hold Your Fire', name: 'Lock and Key', rating: 6 },
{ album: 'Hold Your Fire', name: 'Mission', rating: 7 },
{ album: 'Hold Your Fire', name: 'Turn the Page', rating: 7 },
{ album: 'Hold Your Fire', name: 'Tai Shan', rating: 6 },
{ album: 'Hold Your Fire', name: 'High Water', rating: 6 },

{ album: 'Presto', name: 'Show Don\'t Tell', rating: 6 },
{ album: 'Presto', name: 'Chain Lightning', rating: 7 },
{ album: 'Presto', name: 'The Pass', rating: 7 },
{ album: 'Presto', name: 'War Paint', rating: 7 },
{ album: 'Presto', name: 'Scars', rating: 6 },
{ album: 'Presto', name: 'Presto', rating: 6 },
{ album: 'Presto', name: 'Superconductor', rating: 7 },
{ album: 'Presto', name: 'Anagram for Mongo', rating: 6 },
{ album: 'Presto', name: 'Red Tide', rating: 7 },
{ album: 'Presto', name: 'Hand Over Fist', rating: 6 },
{ album: 'Presto', name: 'Available Light', rating: 8 },

{ album: 'Role the Bones', name: 'Dreamline', rating: 9 },
{ album: 'Role the Bones', name: 'Bravado', rating: 8 },
{ album: 'Role the Bones', name: 'Roll The Bones', rating: 9 },
{ album: 'Role the Bones', name: 'Face Up', rating: 7 },
{ album: 'Role the Bones', name: 'Where\'s My Thing? Part IV, "Gangster Of Boats" Trilogy', rating: 8 },
{ album: 'Role the Bones', name: 'The Big Wheel', rating: 7 },
{ album: 'Role the Bones', name: 'Heresy', rating: 7 },
{ album: 'Role the Bones', name: 'Ghost Of A Chance', rating: 8 },
{ album: 'Role the Bones', name: 'Neurotica', rating: 7 },
{ album: 'Role the Bones', name: 'You Bet Your Life', rating: 10 },

{ album: 'Counterparts', name: 'Animate', rating: 6 },
{ album: 'Counterparts', name: 'Stick It Out', rating: 6 },
{ album: 'Counterparts', name: 'Cut To The Chase', rating: 7 },
{ album: 'Counterparts', name: 'Nobody\'s Hero', rating: 8 },
{ album: 'Counterparts', name: 'Between Sun And Moon', rating: 6 },
{ album: 'Counterparts', name: 'Alien Shore', rating: 7 },
{ album: 'Counterparts', name: 'Speed Of Love', rating: 6 },
{ album: 'Counterparts', name: 'Double Agent', rating: 6 },
{ album: 'Counterparts', name: 'Leave That Thing Alone', rating: 7 },
{ album: 'Counterparts', name: 'Cold Fire', rating: 8 },
{ album: 'Counterparts', name: 'Everyday Glory', rating: 6 },

{ album: 'Test for Echo', name: 'Test For Echo', rating: 7 },
{ album: 'Test for Echo', name: 'Driven', rating: 6 },
{ album: 'Test for Echo', name: 'Half The World', rating: 6 },
{ album: 'Test for Echo', name: 'The Color Of Right', rating: 8 },
{ album: 'Test for Echo', name: 'Time And Motion', rating: 6 },
{ album: 'Test for Echo', name: 'Totem', rating: 7 },
{ album: 'Test for Echo', name: 'Dog Years', rating: 8 },
{ album: 'Test for Echo', name: 'Virtuality', rating: 7 },
{ album: 'Test for Echo', name: 'Resist', rating: 6 },
{ album: 'Test for Echo', name: 'Limbo', rating: 7 },
{ album: 'Test for Echo', name: 'Carve Away The Stone', rating: 6 },

{ album: 'Vapor Trails', name: 'One Little Victory', rating: 8 },
{ album: 'Vapor Trails', name: 'Ceiling Unlimited', rating: 7 },
{ album: 'Vapor Trails', name: 'Ghost Rider', rating: 6 },
{ album: 'Vapor Trails', name: 'Peaceable Kingdom', rating: 6 },
{ album: 'Vapor Trails', name: 'The Stars Look Down', rating: 6 },
{ album: 'Vapor Trails', name: 'How It Is', rating: 9 },
{ album: 'Vapor Trails', name: 'Vapor Trail', rating: 6 },
{ album: 'Vapor Trails', name: 'Secret Touch', rating: 6 },
{ album: 'Vapor Trails', name: 'Earthshine', rating: 6 },
{ album: 'Vapor Trails', name: 'Sweet Miracle', rating: 6 },
{ album: 'Vapor Trails', name: 'Nocturne', rating: 7 },
{ album: 'Vapor Trails', name: 'Freeze Part IV of "Fear"', rating: 6 },
{ album: 'Vapor Trails', name: 'Out Of The Cradle', rating: 8 },

{ album: 'Feedback', name: 'Summertime Blues [Eddie Cochran]', rating: 10 },
{ album: 'Feedback', name: 'Heart Full of Soul [The Yardbirds]', rating: 10 },
{ album: 'Feedback', name: 'For What It\'s Worth [Buffalo Springfield]', rating: 10 },
{ album: 'Feedback', name: 'The Seeker [The Who]', rating: 10 },
{ album: 'Feedback', name: 'Mr. Soul [Buffalo Springfield]', rating: 10 },
{ album: 'Feedback', name: 'Seven And Seven Is [Love]', rating: 10 },
{ album: 'Feedback', name: 'Shapes Of Things [The Yardbirds]', rating: 10 },
{ album: 'Feedback', name: 'Crossroads [Robert Johnson]', rating: 10 },

{ album: 'Snakes & Arrows', name: 'Far Cry', rating: 8 },
{ album: 'Snakes & Arrows', name: 'Armor and Sword', rating: 6 },
{ album: 'Snakes & Arrows', name: 'Workin\' Them Angels', rating: 6 },
{ album: 'Snakes & Arrows', name: 'The Larger Bowl', rating: 7 },
{ album: 'Snakes & Arrows', name: 'Spindrift', rating: 6 },
{ album: 'Snakes & Arrows', name: 'The Main Monkey Business Instrumental', rating: 7 },
{ album: 'Snakes & Arrows', name: 'The Way The Wind Blows', rating: 9 },
{ album: 'Snakes & Arrows', name: 'Hope Instrumental', rating: 7 },
{ album: 'Snakes & Arrows', name: 'Faithless', rating: 7 },
{ album: 'Snakes & Arrows', name: 'Bravest Face', rating: 8 },
{ album: 'Snakes & Arrows', name: 'Good News First', rating: 7 },
{ album: 'Snakes & Arrows', name: 'Malignant Narcissism Instrumental', rating: 9 },
{ album: 'Snakes & Arrows', name: 'We Hold On', rating: 6 },

{ album: 'Clockwork Angels', name: 'Caravan', rating: 0 },
{ album: 'Clockwork Angels', name: 'BU2B', rating: 0 },
{ album: 'Clockwork Angels', name: 'Clockwork Angels', rating: 0 },
{ album: 'Clockwork Angels', name: 'i - The Pedlar', rating: 0 },
{ album: 'Clockwork Angels', name: 'The Anarchist', rating: 0 },
{ album: 'Clockwork Angels', name: 'Carnies', rating: 0 },
{ album: 'Clockwork Angels', name: 'Halo Effect', rating: 0 },
{ album: 'Clockwork Angels', name: 'Seven Cities Of Gold', rating: 0 },
{ album: 'Clockwork Angels', name: 'The Wreckers', rating: 0 },
{ album: 'Clockwork Angels', name: 'Headlong Flight', rating: 0 },
{ album: 'Clockwork Angels', name: 'ii - The Pedlar', rating: 0 },
{ album: 'Clockwork Angels', name: 'BU2B2', rating: 0 },
{ album: 'Clockwork Angels', name: 'Wish Them Well', rating: 0 },
{ album: 'Clockwork Angels', name: 'The Garden', rating: 0 }

];

}]);

