<%@ Page Language="C#" MasterPageFile="~/Main.master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="TitleText" Runat="Server">Stephen King: Jordan Monsell poster</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="HeadingText" Runat="Server">Stephen King: Jordan Monsell poster</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="BodyHTML" Runat="Server">

<h1>Stephen King Poster</h1>

Return to <a href="StephenKing.aspx">Stephen King home page</a><br>

<h2>Jordan Monsell. He has created this vivid poster</h2>
<h3>Hover over images to get tooltip of which Stephen King novel, novella or short-story it represents</h3>
<p>Image Map Generated by <a href="http://www.image-map.net/">http://www.image-map.net/</a></p>
<p>To zoom in and out on Windows, hold down the Ctrl key, then roll your mouse button, or press + and -. Press Ctrl-0 to return browser to normal zoom.</p>
<p>Visit <a href="https://www.wikihow.com/Zoom-out-on-a-Mac">here</a> for the many ways to Zoom in and out, on a Mac</p>
<p>Names were obtained from <a href="https://io9.gizmodo.com/there-are-almost-200-stephen-king-references-on-this-po-1824997224">GIZMODO</a></p>
<p>
    Additions I made:
    <ol>
        <li>The rats tail spells "Do You Love?" and the key says Nona, where it is found 9 times, but it is also found in The Reach 3 times, and The Raft 2 times</li>
        <li>The Esso sign: The key has Big Driver, but Esso also occurs in Cujo, Needful Things, 11-22-63, Roadwork, and Black House.</li>
        <li>Route 27 sign: The key has Willa, but Route 27 is also mentioned in The Tommyknockers and The Jaunt</li>
        <li>The Eclipse: The key has Dolores Claiborne but the very same eclipse is also featured in Gerald's Game</li>
    </ol>
</p>

<!-- Image Map Generated by http://www.image-map.net/ -->
<img id="skimage" src="img/StephenKingReferences.jpg" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Mr. Mercedes" title="Mr. Mercedes" href="" coords="164,292,157,343,164,388,243,391,323,366,332,286,231,213,142,216" shape="poly">
    <area target="" alt="Dolores Claiborne and Gerald's Game" title="Dolores Claiborne and Gerald's Game" href="" coords="3210,200,87" shape="circle">
    <area target="" alt="The Night Flier" title="The Night Flier" href="" coords="523,226,911,445" shape="rect">
    <area target="" alt="Why We're In Vietnam" title="Why We're In Vietnam" href="" coords="943,248,1197,464" shape="rect">
    <area target="" alt="The Langoliers" title="The Langoliers" href="" coords="1388,137,1668,318" shape="rect">
    <area target="" alt="The Dark Tower" title="The Dark Tower" href="" coords="1356,188,1302,273,1296,401,1280,566,1277,782,1223,884,1350,909,1420,782,1404,496" shape="poly">
    <area target="" alt="The New York Times at Special Bargain Rates" title="The New York Times at Special Bargain Rates" href="" coords="1439,416,1674,629" shape="rect">
    <area target="" alt="Rainy Season" title="Rainy Season" href="" coords="1706,257,1922,566" shape="rect">
    <area target="" alt="Rita Hayworth and Shawshank Redemption" title="Rita Hayworth and Shawshank Redemption" href="" coords="1932,283,2193,251,2202,591,2123,575,2123,664,2170,664,2155,750,2107,696,1996,645,1916,664" shape="poly">
    <area target="" alt="The Death of Jack Hamilton" title="The Death of Jack Hamilton" href="" coords="3369,248,3226,327,3115,305,3093,397,3163,502,3296,556,3354,518,3417,337" shape="poly">
    <area target="" alt="The Girl Who Loved Tom Gordon" title="The Girl Who Loved Tom Gordon" href="" coords="3179,728,3121,750,3045,893,3067,966,3121,1036,3274,1039,3280,903,3242,750" shape="poly">
    <area target="" alt="The Shining" title="The Shining" href="" coords="1096,1332,1102,1465,1153,1507,1073,1567,968,1567,879,1507,778,1577,730,1529,800,1411,905,1332,1000,1275" shape="poly">
    <area target="" alt="Children of the Corn" title="Children of the Corn" href="" coords="3309,928,3382,938,3408,1001,3392,1081,3309,1074" shape="poly">
    <area target="" alt="My Pretty Pony" title="My Pretty Pony" href="" coords="857,480,1207,480,1255,734,1197,846,1064,664,968,703,879,633" shape="poly">
    <area target="" alt="Beachworld" title="Beachworld" href="" coords="905,887,1048,966,1096,855,1102,744,1064,674,984,703,927,776" shape="poly">
    <area target="" alt="Graduation Afternoon" title="Graduation Afternoon" href="" coords="673,569,809,601,911,671,943,734,889,788,730,820,704,884,628,877,596,798,469,788,466,712,561,607" shape="poly">
    <area target="" alt="Carrie" title="Carrie" href="" coords="466,442,348,496,355,559,402,677,428,820,434,1036,482,1030,475,680,555,601" shape="poly">
    <area target="" alt="Desperation" title="Desperation" href="" coords="889,1523,1007,1583,1038,1710,914,1799,914,1720,873,1672,841,1586" shape="poly">
    <area target="" alt="Lucky Quarter" title="Lucky Quarter" href="" coords="739,1065,857,1020,863,979,778,947,723,979" shape="poly">
    <area target="" alt="The Dune" title="The Dune" href="" coords="867,973,746,941,739,893,816,861,959,915,1007,947,905,995" shape="poly">
    <area target="" alt="Road Work" title="Road Work" href="" coords="1077,2066,921,2228,965,2266,1181,2266,1245,2209" shape="poly">
    <area target="" alt="Needful Things" title="Needful Things" href="" coords="2240,566,2438,604,2422,877,2231,858" shape="poly">
    <area target="" alt="The Ledge" title="The Ledge" href="" coords="2581,709,2523,683,2479,731,2444,836,2454,925,2603,922" shape="poly">
    <area target="" alt="The Running Man" title="The Running Man" href="" coords="2447,601,2438,725,2517,680,2597,687,2590,623" shape="poly">
    <area target="" alt="Cain Rose Up" title="Cain Rose Up" href="" coords="2454,401,2460,575,2597,614,2692,661,2574,496,2571,426" shape="poly">
    <area target="" alt="Esso Sign: Big Driver, Cujo, Needful Things, 11-22-63, Roadwork, Black House" title="Big Driver, Cujo, Needful Things, 11-22-63, Roadwork, Black House" href="" coords="2587,394,2644,331,2714,337,2740,385,2708,455,2613,458" shape="poly">
    <area target="" alt="Hearts in Atlantis" title="Hearts in Atlantis" href="" coords="2523,283,2495,312,2479,343,2485,385,2523,407,2565,385,2549,305" shape="poly">
    <area target="" alt="The Boogeyman" title="The Boogeyman" href="" coords="2129,585,2129,664,2174,671,2167,757,2205,798,2221,655,2225,607" shape="poly">
    <area target="" alt="The House on Maple Street" title="The House on Maple Street" href="" coords="1706,690,1668,718,1668,944,1595,982,1706,1030,1741,1024,1817,966,1732,950,1732,728" shape="poly">
    <area target="" alt="Under the Dome" title="Under the Dome" href="" coords="1302,1001,1414,823,1563,690,1817,636,1913,664,1837,712,1805,776,1837,865,1875,919,1827,960,1738,935,1741,737,1706,690,1668,712,1658,935,1604,982,1693,1030" shape="poly">
    <area target="" alt="Dreamcatcher" title="Dreamcatcher" href="" coords="2663,950,38" shape="circle">
    <area target="" alt="Uncle Otto's Truck" title="Uncle Otto's Truck" href="" coords="3210,1109,3296,1103,3338,1148,3379,1179,3268,1205,3268,1157" shape="poly">
    <area target="" alt="The Lawnmower Man" title="The Lawnmower Man" href="" coords="3408,1186,3338,1287,3255,1281,3280,1233,3338,1195" shape="poly">
    <area target="" alt="Insomnia" title="Insomnia" href="" coords="720,979,698,919,650,909,612,963,587,1059,593,1132,650,1138,704,1163" shape="poly">
    <area target="" alt="Afterlife" title="Afterlife" href="" coords="412,1046,507,1030,571,1036,577,1141,498,1125,437,1148" shape="poly">
    <area target="" alt="The Outsider" title="The Outsider" href="" coords="253,1030,332,1062,402,1046,428,1157,342,1151,301,1109,301,1163,246,1243" shape="poly">
    <area target="" alt="The Outsider" title="The Outsider" href="" coords="491,1132,460,1195,482,1284,444,1322,564,1316,571,1189,587,1148" shape="poly">
    <area target="" alt="The Outsider" title="The Outsider" href="" coords="714,1090,778,1103,841,1151,762,1230,720,1119" shape="poly">
    <area target="" alt="The Reaper's Image" title="The Reaper's Image" href="" coords="596,1141,650,1141,698,1163,714,1125,755,1237,768,1341,730,1434,689,1364,714,1332,682,1262,634,1230,571,1259,571,1183" shape="poly">
    <area target="" alt="Cycle of the Werewolf" title="Cycle of the Werewolf" href="" coords="307,1113,307,1167,275,1214,275,1278,294,1335,269,1383,259,1437,291,1485,285,1415,301,1389,355,1411,402,1383,421,1415,421,1494,301,1564,291,1653,348,1685,364,1707,364,1761,386,1834,418,1532,444,1580,498,1494,539,1453,491,1421,475,1453,437,1367,405,1326,491,1278,466,1189,491,1128,428,1151,348,1144" shape="poly">
    <area target="" alt="The Doctor's Case" title="The Doctor's Case" href="" coords="460,1338,491,1354,523,1376,571,1415,539,1446,482,1415" shape="poly">
    <area target="" alt="Handcuffs: Gerald's Game" title="Gerald's Game" href="" coords="739,1672,857,1688,863,1736,746,1736" shape="poly">
    <area target="" alt="That Bus Is Another World" title="That Bus Is Another World" href="" coords="634,1376,698,1383,698,1415,628,1415,612,1678,577,1678,580,1456" shape="poly">
    <area target="" alt="Rose Madder" title="Rose Madder" href="" coords="571,1265,634,1233,682,1272,714,1329,682,1351,619,1361,596,1376,603,1405,577,1424,501,1351,580,1313" shape="poly">
    <area target="" alt="Rose Madder" title="Rose Madder" href="" coords="634,1418,619,1666,603,1691,603,1850,625,2054,666,2054,666,1888,698,2127,746,2079,736,1898,778,1866,755,1761,723,1659,768,1666,730,1427" shape="poly">
    <area target="" alt="Thinner" title="Thinner" href="" coords="571,1491,491,1532,418,1628,418,1691,482,1713,571,1701" shape="poly">
    <area target="" alt="Graveyard Shift" title="Graveyard Shift" href="" coords="183,505,253,490,291,518,316,648,301,677,205,633,211,575,205,537" shape="poly">
    <area target="" alt="Cookie Jar" title="Cookie Jar" href="" coords="103,496,164,509,205,534,199,598,157,604,100,575" shape="poly">
    <area target="" alt="Do You Love? Nona, The Reach, The Raft" title="Nona, The Reach, The Raft" href="" coords="301,680,332,664,380,687,412,750,364,782,301,703" shape="poly">
    <area target="" alt="Dragon Head: The Eyes of the Dragon" title="Dragon Head: The Eyes of the Dragon" href="" coords="119,639,285,709,390,884,405,1036,336,1052,256,1020,151,1036,103,935" shape="poly">
    <area target="" alt="The Body" title="The Body" href="" coords="97,1084,142,1160,237,1052" shape="poly">
    <area target="" alt="Weeds" title="Weeds" href="" coords="135,1367,183,1383,205,1424,237,1405,253,1446,215,1469,215,1510,221,1542,183,1526,145,1478,119,1456" shape="poly">
    <area target="" alt="I Am the Doorway" title="I Am the Doorway" href="" coords="129,1570,157,1539,183,1586,205,1634,167,1713,177,1745,142,1761,113,1739" shape="poly">
    <area target="" alt="The Green Mile" title="The Green Mile" href="" coords="173,1183,103,1291,113,1411,126,1364,189,1386,205,1411,240,1395,256,1418,262,1332,237,1278" shape="poly">
    <area target="" alt="The Green Mile" title="The Green Mile" href="" coords="110,1421,103,1459,103,1697,135,1554,157,1532,205,1634,183,1704,189,1745,145,1752,103,1752,103,1993,161,2095,294,2101,453,2025,396,1968,374,1802,364,1697,294,1643,294,1513,262,1453,224,1497,224,1545,167,1516" shape="poly">
    <area target="" alt="A Good Marriage" title="A Good Marriage" href="" coords="739,1933,730,1980,755,1987,781,1965,781,1933" shape="poly">
    <area target="" alt="All That You Love Will Be Carried Away" title="All That You Love Will Be Carried Away" href="" coords="463,1726,603,1726,590,1834,501,1774" shape="poly">
    <area target="" alt="The Monkey" title="The Monkey" href="" coords="437,1755,485,1755,526,1799,539,1863,539,1895,479,1920,437,1898,405,1809" shape="poly">
    <area target="" alt="Gramma" title="Gramma" href="" coords="304,1395,361,1421,399,1389,421,1411,409,1491,367,1507,297,1485,288,1411" shape="poly">
    <area target="" alt="Autopsy Room Four" title="Autopsy Room Four" href="" coords="107,2073,167,2095,177,2165,240,2168,288,2120,326,2133,281,2165,224,2206,145,2200,135,2127,97,2127" shape="poly">
    <area target="" alt="Harvey's Dream" title="Harvey's Dream" href="" coords="367,2197,453,2203,415,2266,361,2244" shape="poly">
    <area target="" alt="The Ballad of the Flexible Bullet" title="The Ballad of the Flexible Bullet" href="" coords="590,1910,501,1942,501,2006,504,2076,558,2108,596,2092,596,2012" shape="poly">
    <area target="" alt="Misery" title="Misery" href="" coords="479,2082,510,2082,564,2123,622,2123,599,2066,660,2060,701,2200,542,2241,488,2193" shape="poly">
    <area target="" alt="Battleground" title="Battleground" href="" coords="746,2120,851,2143,835,2232,714,2209" shape="poly">
    <area target="" alt="Heavenly Shades of Night are Falling" title="Heavenly Shades of Night are Falling" href="" coords="835,1866,889,1904,851,2136,755,2111" shape="poly">
    <area target="" alt="Crouch End" title="Crouch End" href="" coords="905,1742,844,1764,835,1818,857,1875,908,1907,962,1971,946,2009,876,2050,851,2152,835,2263,930,2263,914,2171,914,2123,962,2082,1000,2025,1000,1987,956,1907,898,1866,867,1821" shape="poly">
    <area target="" alt="Jerusalem's Lot" title="Jerusalem's Lot" href="" coords="962,976,905,1005,876,1062,844,1148,765,1237,793,1259,851,1284,937,1262,962,1189,1032,1103,1042,1062,1003,1005" shape="poly">
    <area target="" alt="The Library Policeman" title="The Library Policeman" href="" coords="1258,1265,1232,1303,1162,1335,1153,1402,1216,1402,1248,1446,1290,1440,1296,1392" shape="poly">
    <area target="" alt="1922" title="1922" href="" coords="1153,1386,1099,1402,1105,1443,1175,1459,1239,1443,1210,1405" shape="poly">
    <area target="" alt="The Crate" title="The Crate" href="" coords="1280,1306,1328,1284,1398,1297,1385,1322,1360,1338,1290,1322" shape="poly">
    <area target="" alt="'Salem's Lot" title="'Salem's Lot" href="" coords="2781,931,2816,1011,2705,1011,2727,947" shape="poly">
    <area target="" alt="N." title="N." href="" coords="2209,995,2145,1074,2145,1154,2234,1154,2304,1148,2298,1059" shape="poly">
    <area target="" alt="The Last Rung on the Ladder" title="The Last Rung on the Ladder" href="" coords="2314,941,2384,941,2463,1090,2403,1148,2361,1122,2323,1036" shape="poly">
    <area target="" alt="Popsy" title="Popsy" href="" coords="2689,801,2765,779,2854,849,2902,976,2911,842,2966,769,3045,817,2975,960,3013,1046,2934,1103,3020,1109,2959,1230,2896,1167,2775,1103,2822,1049" shape="poly">
    <area target="" alt="The Moving Finger Hands" title="The Moving Finger Hands" href="" coords="1852,706,1948,658,2018,664,2113,699,2101,760,2053,769,1980,753,1900,807,1910,865,1878,919,1805,779" shape="poly">
    <area target="" alt="Chattery Teeth" title="Chattery Teeth" href="" coords="1926,871,1938,957,1932,989,1996,998,2085,992,2123,941,2107,887,2145,849,2116,823,2075,839" shape="poly">
    <area target="" alt="My Pretty Pony" title="My Pretty Pony" href="" coords="2304,1122,2304,1176,2361,1186,2393,1186,2371,1138" shape="poly">
    <area target="" alt="Revival" title="Revival" href="" coords="2361,1205,2298,1237,2244,1252,2228,1332,2202,1411,2240,1395,2272,1389,2298,1357,2345,1322,2415,1373,2393,1459,2473,1497,2504,1418,2511,1373,2504,1332,2441,1275,2489,1268,2457,1205" shape="poly">
    <area target="" alt="Batman and Robin Have an Altercation" title="Batman and Robin Have an Altercation" href="" coords="2498,1310,2514,1373,2546,1373,2568,1341,2536,1300" shape="poly">
    <area target="" alt="IT" title="IT" href="" coords="1970,1465,1996,1395,2027,1341,2085,1348,2116,1418,2059,1434,2097,1497,2139,1570,2202,1539,2250,1570,2256,1624,2240,1729,2196,1745,2116,1723,2123,1612,2085,1532,2011,1459" shape="poly">
    <area target="" alt="IT" title="IT" href="" coords="2240,1424,2212,1446,2225,1488,2240,1558,2260,1497,2282,1450,2266,1424" shape="poly">
    <area target="" alt="A Very Tight Place" title="A Very Tight Place" href="" coords="1954,1488,2011,1647,1980,1663,1942,1615,1916,1519" shape="poly">
    <area target="" alt="The Mangler" title="The Mangler" href="" coords="2075,1450,2123,1443,2177,1450,2202,1475,2170,1504,2101,1491" shape="poly">
    <area target="" alt="The Body" title="The Body" href="" coords="2043,1682,1942,1682,1926,1783,1932,1847,1996,1920,2050,1898" shape="poly">
    <area target="" alt="The Raft" title="The Raft" href="" coords="1922,1783,1868,1802,1852,1872,1970,1968,2027,1968,2139,1926,2161,1942,2234,1898,2164,1834,2053,1818,2050,1879,2005,1904,1922,1841" shape="poly">
    <area target="" alt="Pet Sematary" title="Pet Sematary" href="" coords="2116,1933,2075,1955,2059,2006,2091,2034,2155,2076,2177,2069,2202,2003,2186,1971" shape="poly">
    <area target="" alt="Bag of Bones" title="Bag of Bones" href="" coords="2415,1748,2304,1742,2250,1774,2266,1812,2314,1853,2361,1853,2361,1815,2431,1831,2419,1863,2447,1863,2489,1799,2434,1783" shape="poly">
    <area target="" alt="Mute" title="Mute" href="" coords="2371,1828,2425,1834,2419,1898,2361,1875" shape="poly">
    <area target="" alt="The Stand" title="The Stand" href="" coords="2520,1860,2466,1844,2434,1882,2431,1920,2479,1977,2536,2025" shape="poly">
    <area target="" alt="The Reach" title="The Reach" href="" coords="2695,1742,2625,1666,2552,1678,2489,1790,2520,1863,2539,1942,2673,1872,2654,1809" shape="poly">
    <area target="" alt="Doctor Sleep" title="Doctor Sleep" href="" coords="2679,1710,2743,1688,2797,1726,2838,1942,2743,1974,2663,1806,2686,1758" shape="poly">
    <area target="" alt="Obits" title="Obits" href="" coords="1089,1014,1153,906,1207,1024" shape="poly">
    <area target="" alt="Willa, The Jaunt, The Tommyknockers" title="Willa, The Jaunt, The Tommyknockers" href="" coords="1210,966,1280,982,1258,1030,1216,1024" shape="poly">
    <area target="" alt="11-22-63" title="11-22-63" href="" coords="1302,1046,1407,1014,1464,1024,1525,1055,1528,1103,1290,1100" shape="poly">
    <area target="" alt="The Long Walk" title="The Long Walk" href="" coords="1439,1186,1573,1179,1582,1306,1528,1275,1455,1291,1449,1243" shape="poly">
    <area target="" alt="Joyland" title="Joyland" href="" coords="1509,1275,1455,1297,1407,1322,1461,1370,1407,1402,1445,1434,1477,1411,1430,1504,1493,1608,1541,1608,1566,1529,1544,1411,1589,1427,1630,1386,1576,1386,1534,1364,1573,1322" shape="poly">
    <area target="" alt="From A Buick 8" title="From A Buick 8" href="" coords="1700,1202,1732,1179,1798,1170,1837,1202,1830,1217,1798,1233,1709,1217" shape="poly">
    <area target="" alt="Trucks" title="Trucks" href="" coords="1115,1017,1057,1071,1064,1119,1153,1113,1146,1151,1439,1198,1477,1176,1566,1176,1582,1208,1636,1208,1623,1160,1550,1106,1169,1081,1169,1027" shape="poly">
    <area target="" alt="That Feeling, You Can Only Say What It Is in French" title="That Feeling, You Can Only Say What It Is in French" href="" coords="1573,1039,1732,1033,1684,1135,1566,1119" shape="poly">
    <area target="" alt="Mile 81" title="Mile 81" href="" coords="1258,1195,1375,1195,1414,1233,1375,1259,1321,1259,1248,1233" shape="poly">
    <area target="" alt="Bad Little Kid" title="Bad Little Kid" href="" coords="1678,1227,1630,1287,1693,1402,1767,1392,1783,1345,1741,1275" shape="poly">
    <area target="" alt="Suffer the Little Children" title="Suffer the Little Children" href="" coords="1773,1399,1687,1405,1566,1446,1573,1504,1630,1526" shape="poly">
    <area target="" alt="LT's Theory of Pets" title="LT's Theory of Pets" href="" coords="1121,1450,1366,1529,1350,1577,1312,1561,1121,1472" shape="poly">
    <area target="" alt="Summer Thunder" title="Summer Thunder" href="" coords="1398,1459,1360,1513,1391,1539,1430,1485" shape="poly">
    <area target="" alt="Cujo" title="Cujo" href="" coords="1248,1485,1312,1469,1366,1485,1353,1516" shape="poly">
    <area target="" alt="Cujo" title="Cujo" href="" coords="1366,1523,1401,1539,1423,1624,1417,1688,1385,1790,1350,1761,1242,1726,1223,1631,1232,1523,1350,1577" shape="poly">
    <area target="" alt="Strawberry Spring" title="Strawberry Spring" href="" coords="1137,1783,1344,1761,1337,1831,1137,1847" shape="poly">
    <area target="" alt="Under the Weather" title="Under the Weather" href="" coords="1302,1844,1382,1837,1385,1885,1305,1875" shape="poly">
    <area target="" alt="Mrs. Todd's Shortcut" title="Mrs. Todd's Shortcut" href="" coords="1169,2015,1216,2009,1270,2015,1334,2073,1232,2073,1169,2057" shape="poly">
    <area target="" alt="Christine" title="Christine" href="" coords="1423,1596,1598,1961,1566,2041,1328,2095,1321,2057,1264,2003,1169,2009,1185,2066,1242,2079,1048,2088,1035,1993,1185,1580,1216,1586,1248,1729,1318,1748,1137,1771,1131,1834,1296,1834,1302,1872,1382,1882,1391,1825,1344,1818,1350,1771,1382,1786,1414,1723" shape="poly">
    <area target="" alt="Rest Stop" title="Rest Stop" href="" coords="1480,1656,1646,1608,1678,1647,1503,1694" shape="poly">
    <area target="" alt="Misery" title="Misery" href="" coords="1859,1440,1783,1434,1716,1472,1678,1494,1646,1583,1684,1605,1779,1637,1875,1535" shape="poly">
    <area target="" alt="The Little Green Agony of God" title="The Little Green Agony of God" href="" coords="1900,1211,1932,1211,1932,1233,1894,1240" shape="poly">
    <area target="" alt="Word Processor of the Gods" title="Word Processor of the Gods" href="" coords="2011,1332,1932,1370,1910,1348,1938,1300,1996,1300" shape="poly">
    <area target="" alt="The Wedding Gig" title="The Wedding Gig" href="" coords="1932,1297,1827,1303,1805,1392,1852,1430,1900,1494,1973,1456,2018,1338,1922,1367,1900,1345" shape="poly">
    <area target="" alt="The Wedding Gig" title="The Wedding Gig" href="" coords="2059,1281,1957,1173,1875,1179,1862,1211,1942,1211,1932,1291,1989,1297,2034,1338" shape="poly">
    <area target="" alt="The Wedding Gig" title="The Wedding Gig" href="" coords="1859,1211,1821,1306,1932,1291,1926,1237,1891,1243,1884,1205" shape="poly">
    <area target="" alt="Weeds" title="Weeds" href="" coords="2139,1176,2107,1208,2132,1233,2155,1240,2164,1195" shape="poly">
    <area target="" alt="A Death" title="A Death" href="" coords="2145,1170,2164,1195,2155,1243,2234,1243,2256,1217,2202,1173" shape="poly">
    <area target="" alt="A Death" title="A Death" href="" coords="2139,1173,2091,1230,2091,1167" shape="poly">
    <area target="" alt="Riding the Bullet" title="Riding the Bullet" href="" coords="2091,1243,2101,1297,2225,1376,2234,1265" shape="poly">
    <area target="" alt="Quitter's Inc." title="Quitter's Inc." href="" coords="3420,2054,3427,2133,3474,2165,3481,2044" shape="poly">
    <area target="" alt="The Ten O'Clock People" title="The Ten O'Clock People" href="" coords="3452,1879,3481,1980,3474,2022,3411,2054,3427,2133,3458,2181,3417,2276,3204,2260,3290,2031,3274,1904,3284,1841,3373,1895,3427,1901" shape="poly">
    <area target="" alt="The Gingerbread Girl" title="The Gingerbread Girl" href="" coords="3007,1930,3004,1987,3086,2015,3045,1939" shape="poly">
    <area target="" alt="Grey Matter" title="Grey Matter" href="" coords="3023,1831,3182,1799,3268,2054,3125,2181,3109,2276,2927,2270,2966,2038,3055,2006,3093,2022,3067,1974" shape="poly">
    <area target="" alt="The Jaunt" title="The Jaunt" href="" coords="2902,1974,2934,1980,2972,1974,2997,1958,2997,1917,2950,1885,2918,1901,2896,1926" shape="poly">
    <area target="" alt="Premium Harmony" title="Premium Harmony" href="" coords="2902,1974,2927,1984,2972,1974,2966,2015,2896,2063,2832,2028" shape="poly">
    <area target="" alt="Here There Be Tygers" title="Here There Be Tygers" href="" coords="2781,2063,2705,2104,2702,2143,2752,2168,2781,2136" shape="poly">
    <area target="" alt="The Sun Dog" title="The Sun Dog" href="" coords="2807,2155,2711,2209,2727,2273,2908,2257,2864,2197" shape="poly">
    <area target="" alt="Lunch at the Gotham Cafe" title="Lunch at the Gotham Cafe" href="" coords="2250,2060,2447,2123,2479,2193,2425,2266,2260,2266,2218,2212" shape="poly">
    <area target="" alt="Fair Extension" title="Fair Extension" href="" coords="2298,1926,2298,1958,2377,1952,2377,1926" shape="poly">
    <area target="" alt="Morality" title="Morality" href="" coords="2361,1866,2304,1866,2282,1920,2399,1920" shape="poly">
    <area target="" alt="Morality" title="Morality" href="" coords="2282,1933,2250,1939,2330,2076,2384,2098,2399,1933,2371,1955,2298,1965" shape="poly">
    <area target="" alt="Morning Deliveries (Milkman #1)" title="Morning Deliveries (Milkman #1)" href="" coords="2447,2006,2498,2006,2504,2117,2457,2111" shape="poly">
    <area target="" alt="The Woman in the Room" title="The Woman in the Room" href="" coords="2504,2060,2504,2098,2568,2098,2562,2054" shape="poly">
    <area target="" alt="Duma Key" title="Duma Key" href="" coords="2702,1910,2737,1990,2679,2054,2625,2006,2638,1942" shape="poly">
    <area target="" alt="The Road Virus Heads North" title="The Road Virus Heads North" href="" coords="2743,1996,2807,2022,2663,2101,2498,2155,2457,2139,2450,2101,2504,2101,2568,2101,2574,2044,2638,2022,2679,2050" shape="poly">
    <area target="" alt="Cell" title="Cell" href="" coords="1859,2149,1932,2219,2011,2197,1980,2123" shape="poly">
    <area target="" alt="Everything's Eventual" title="Everything's Eventual" href="" coords="1827,2095,1964,2263,1620,2263,1614,2177,1678,2120" shape="poly">
    <area target="" alt="Stationary Bike" title="Stationary Bike" href="" coords="1487,2263,1464,2216,1541,2158,1544,2117,1573,2015,1598,2069,1646,2088,1678,2079,1614,2181,1608,2276" shape="poly">
    <area target="" alt="Home Delivery" title="Home Delivery" href="" coords="1875,1949,1980,2098,1846,2104,1798,2076,1693,2088,1623,2060,1773,1980,1811,1933" shape="poly">
    <area target="" alt="I Know What You Need" title="I Know What You Need" href="" coords="1375,2136,1375,2174,1414,2206,1461,2222,1493,2177,1449,2136" shape="poly">
    <area target="" alt="Survivor Type" title="Survivor Type" href="" coords="1280,2184,1375,2200,1360,2232,1264,2209" shape="poly">
    <area target="" alt="Sometimes They Come Back" title="Sometimes They Come Back" href="" coords="1360,2139,1201,2162,1248,2216,1280,2177,1391,2200" shape="poly">
    <area target="" alt="Sometimes They Come Back" title="Sometimes They Come Back" href="" coords="1255,2206,1360,2228,1391,2197,1461,2228,1477,2260,1201,2270" shape="poly">
    <area target="" alt="It Grows On You" title="It Grows On You" href="" coords="1668,1678,1703,1694,1671,1720" shape="poly">
    <area target="" alt="Blind Willie" title="Blind Willie" href="" coords="1716,1831,1748,1853,1652,2028,1623,2006" shape="poly">
    <area target="" alt="1408" title="1408" href="" coords="1757,1856,1693,1952,1732,1977,1757,1952" shape="poly">
    <area target="" alt="Umney's Last Case" title="Umney's Last Case" href="" coords="1550,1691,1652,1659,1668,1723,1693,1755,1757,1771,1757,1844,1719,1818,1678,1872,1639,1898,1592,1875,1598,1834,1668,1812,1589,1755" shape="poly">
    <area target="" alt="Umney's Last Case" title="Umney's Last Case" href="" coords="1671,1669,1725,1640,1798,1710,1751,1758,1693,1752,1671,1720,1709,1694" shape="poly">
    <area target="" alt="UR" title="UR" href="" coords="2931,1850,2969,1850,2985,1872,2931,1879" shape="poly">
    <area target="" alt="Firestarter" title="Firestarter" href="" coords="2956,1707,2985,1720,3016,1723,3048,1707,3058,1755,3112,1739,3115,1767,3051,1815,3026,1825,3026,1856,2985,1872,2962,1841,2924,1729" shape="poly">
    <area target="" alt="The Girl Who Loved Tom Gordon" title="The Girl Who Loved Tom Gordon" href="" coords="3004,1659,2978,1672,2969,1707,3016,1713,3048,1697,3032,1666" shape="poly">
    <area target="" alt="Ayana" title="Ayana" href="" coords="2851,1621,2889,1628,2892,1685,2877,1812,2829,1802,2803,1726,2803,1637" shape="poly">
    <area target="" alt="Lisey's Story" title="Lisey's Story" href="" coords="2565,1405,2606,1507,2654,1494,2606,1389" shape="poly">
    <area target="" alt="The Breathing Method" title="The Breathing Method" href="" coords="2565,1421,2597,1469,2527,1485,2523,1430" shape="poly">
    <area target="" alt="The Little Sisters of Eluria" title="The Little Sisters of Eluria" href="" coords="2523,1485,2587,1469,2597,1500,2651,1516,2689,1577,2628,1586,2533,1554" shape="poly">
    <area target="" alt="The End of the Whole Mess" title="The End of the Whole Mess" href="" coords="2527,1549,2632,1584,2676,1562,2692,1587,2804,1676,2778,1708,2679,1613,2644,1657,2511,1609" shape="poly">
    <area target="" alt="The Things They Left Behind" title="The Things They Left Behind" href="" coords="2644,1657,2686,1625,2721,1648,2692,1679" shape="poly">
    <area target="" alt="Dedication" title="Dedication" href="" coords="2492,1596,2539,1618,2533,1688,2469,1675,2454,1628" shape="poly">
    <area target="" alt="The Man in the Black Suit" title="The Man in the Black Suit" href="" coords="2364,1421,2342,1446,2304,1589,2358,1621,2422,1621,2454,1567,2390,1430" shape="poly">
    <area target="" alt="The Man Who Loved Flowers" title="The Man Who Loved Flowers" href="" coords="2644,1351,2613,1380,2635,1411,2667,1373" shape="poly">
    <area target="" alt="Low Men in Yellow Coats" title="Low Men in Yellow Coats" href="" coords="2714,1214,2772,1341,2670,1364,2644,1326,2638,1278,2660,1240" shape="poly">
    <area target="" alt="The Tommyknockers" title="The Tommyknockers" href="" coords="2514,1119,2492,1167,2514,1237,2482,1300,2523,1294,2555,1192,2565,1119" shape="poly">
    <area target="" alt="A Death" title="A Death" href="" coords="2492,947,2469,1074,2482,1151,2514,1113,2523,947" shape="poly">
    <area target="" alt="Night Surf" title="Night Surf" href="" coords="3344,1669,3398,1615,3452,1643,3493,1605,3487,1230,3191,1446,3245,1548,3296,1643" shape="poly">
    <area target="" alt="The Tommyknockers" title="The Tommyknockers" href="" coords="2549,257,2730,216,2959,210,3112,289,3070,381,3201,582,3341,788,3430,970,3478,1059,3468,1122,3487,1224,3455,1240,3436,1090,3423,1005,3328,836,3217,687,2985,470,2851,486,2756,423,2730,321,2613,312" shape="poly">
    <area target="" alt="The Mist" title="The Mist" href="" coords="2746,416,2717,455,2654,493,2819,731,2826,811,2889,900,2915,804,2978,699,3080,671,3096,763,3121,734,3144,671,3144,715,3185,715,3191,661,2978,470,2845,486" shape="poly">
    <area target="" alt="The Mist" title="The Mist" href="" coords="3493,334,3487,731,3382,645,3446,890,3404,896,3350,683,3303,620,3264,642,3169,509,3309,556,3357,518,3414,334" shape="poly">
    <area target="" alt="You Know They Got a Hell of a Band" title="You Know They Got a Hell of a Band" href="" coords="2803,1221,2962,1256,3121,1246,3105,1294,2962,1316,2813,1272" shape="poly">
    <area target="" alt="The Dead Zone" title="The Dead Zone" href="" coords="2915,1335,2803,1380,2915,1430,2962,1443,3016,1443,3121,1405,3036,1335" shape="poly">
    <area target="" alt="The Dark Half" title="The Dark Half" href="" coords="2803,1427,2873,1408,2969,1440,3032,1434,3074,1481,3058,1535,2937,1710,2889,1697,2896,1624" shape="poly">
    <area target="" alt="Secret Window, Secret Garden" title="Secret Window, Secret Garden" href="" coords="3112,1682,3150,1666,3223,1707,3175,1729,3105,1697" shape="poly">
    <area target="" alt="Apt Pupil" title="Apt Pupil" href="" coords="3398,1621,3290,1732,3312,1818,3408,1891,3446,1869,3493,1875,3487,1701,3455,1637" shape="poly">
    <area target="" alt="The Man Who Would Not Shake Hands" title="The Man Who Would Not Shake Hands" href="" coords="3207,1634,3191,1666,3223,1691,3239,1653" shape="poly">
    <area target="" alt="The Cat From Hell" title="The Cat From Hell" href="" coords="3185,1564,3214,1564,3239,1605,3201,1621,3185,1583" shape="poly">
    <area target="" alt="The Fifth Quarter" title="The Fifth Quarter" href="" coords="3153,1469,3217,1539,3210,1561,3185,1570,3131,1548" shape="poly">
    <area target="" alt="The Colorado Kid" title="The Colorado Kid" href="" coords="3064,1567,3137,1542,3175,1567,3201,1615,3255,1589,3280,1663,3201,1685,3147,1663,3080,1669" shape="poly">
    <area target="" alt="The Reach" title="The Reach" href="" coords="2247,1926,2177,1958,2199,2019,2190,2054,2253,2060,2310,2044" shape="poly">
    <area target="" alt="The Reach" title="The Reach" href="" coords="2396,1888,2428,1910,2476,1974,2396,1999,2396,1917" shape="poly">
    <area target="" alt="The Ballad of the Flexible Bullet" title="The Ballad of the Flexible Bullet" href="" coords="472,2114,479,2200,370,2177,425,2120" shape="poly">
    <area target="" alt="Big Wheels: A Tale of the Laundry Game (Milman #2)" title="Big Wheels: A Tale of the Laundry Game (Milman #2)" href="" coords="2517,2143,2517,2232,2565,2260,2587,2247,2587,2158" shape="poly">
    <area target="" alt="Blaze" title="Blaze" href="" coords="2613,1128,2584,1170,2616,1208,2644,1176" shape="poly">
    <area target="" alt="Under the Dome" title="Under the Dome" href="" coords="2708,1472,2644,1504,2670,1542,2797,1529,2756,1481" shape="poly">
</map>

</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="CreatedDateText" Runat="Server">February 1, 2020</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="UpdatedDateText" Runat="Server">March 6, 2021</asp:Content>
